/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes.MatriculaCurso;
import Classes.MatriculaCursoDAO;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Emanoel
 */
public class InterfaceCadastroMatricula extends javax.swing.JInternalFrame {

    /**
     * Creates new form InterfaceCadastroMatricula
     */
    JDesktopPane desktop = null;
    int i = -1;
    int cursoAntigo;

    public InterfaceCadastroMatricula() {
        initComponents();
    }

    public InterfaceCadastroMatricula(JDesktopPane desktop, int i) {
        this.i = i;
        this.desktop = desktop;
        initComponents();
        if (i == 1) {
            jbSelecionarMatricula.setVisible(true);
            jtfCodigo.setEditable(false);
            jbSelecionarAluno.setEnabled(false);
            jbSelecionarCurso.setEnabled(false);
            jbCadastrar.setText("Atualizar");
        } else {
            jbSelecionarMatricula.setVisible(false);
        }
    }
    
    public void completar (String codigo, String matricula, String codCurso, String data){
        jtfCodigo.setText(codigo);
        jtfMatriculaAluno.setText(matricula);
        jtfCodCurso.setText(codCurso);
        jtfData.setText(data);
        jbSelecionarAluno.setEnabled(true);
        jbSelecionarCurso.setEnabled(true);
        this.cursoAntigo = Integer.parseInt(codCurso);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbCadastrar = new javax.swing.JButton();
        jbFechar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jtfMatriculaAluno = new javax.swing.JTextField();
        jtfCodCurso = new javax.swing.JTextField();
        jtfData = new javax.swing.JTextField();
        jbSelecionarAluno = new javax.swing.JButton();
        jbSelecionarCurso = new javax.swing.JButton();
        jbSelecionarMatricula = new javax.swing.JButton();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cadastro Matricula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jbCadastrar.setText("Cadastrar");
        jbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarActionPerformed(evt);
            }
        });

        jbFechar.setText("Fechar");
        jbFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbFecharActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo:");

        jLabel2.setText("Matricula Aluno:");

        jLabel3.setText("Codigo Curso:");

        jLabel4.setText("Data Matricula:");

        jtfMatriculaAluno.setEditable(false);

        jtfCodCurso.setEditable(false);

        jbSelecionarAluno.setText("...");
        jbSelecionarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelecionarAlunoActionPerformed(evt);
            }
        });

        jbSelecionarCurso.setText("...");
        jbSelecionarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelecionarCursoActionPerformed(evt);
            }
        });

        jbSelecionarMatricula.setText("...");
        jbSelecionarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelecionarMatriculaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfData, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                    .addComponent(jtfCodigo)
                    .addComponent(jtfMatriculaAluno)
                    .addComponent(jtfCodCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSelecionarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSelecionarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSelecionarMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jbCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSelecionarMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfMatriculaAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSelecionarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfCodCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSelecionarCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCadastrar)
                    .addComponent(jbFechar)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        Date date = new Date();
        SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
        jtfData.setText(formatador.format(date));
    }//GEN-LAST:event_formInternalFrameActivated

    private void jbFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbFecharActionPerformed

    private void jbSelecionarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelecionarAlunoActionPerformed
        InterfaceRelatório form = new InterfaceRelatório(0, jtfMatriculaAluno);
        form.setLocation((desktop.getSize().width - form.getSize().width) / 2, (desktop.getSize().height - form.getSize().height) / 2);
        desktop.add(form);
        form.setVisible(true);
    }//GEN-LAST:event_jbSelecionarAlunoActionPerformed

    private void jbSelecionarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelecionarCursoActionPerformed
        InterfaceRelatório form = new InterfaceRelatório(1, jtfCodCurso);
        form.setLocation((desktop.getSize().width - form.getSize().width) / 2, (desktop.getSize().height - form.getSize().height) / 2);
        desktop.add(form);
        form.setVisible(true);
        
    }//GEN-LAST:event_jbSelecionarCursoActionPerformed

    private void jbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarActionPerformed
        MatriculaCursoDAO matriculaDAO = new MatriculaCursoDAO();
        if (this.i == 0) {
            try {
                    matriculaDAO.cadastra(new MatriculaCurso(Integer.parseInt(jtfCodigo.getText()), Integer.parseInt(jtfMatriculaAluno.getText()), Integer.parseInt(jtfCodCurso.getText()), jtfData.getText()));
                    limpaCampos();
            } catch (NumberFormatException numberFormatException) {
                JOptionPane.showMessageDialog(null, "Campos Inválidos!");
                return;
            }
        } else {
            try { 
                    matriculaDAO.AtualizarMatriculaCurso(Integer.parseInt(jtfCodigo.getText()), Integer.parseInt(jtfMatriculaAluno.getText()), Integer.parseInt(jtfCodCurso.getText()), jtfData.getText());
                    JOptionPane.showMessageDialog(null, "Matricula Atualizada com sucesso!");
            } catch (NumberFormatException numberFormatException) {
                JOptionPane.showMessageDialog(null, "Campos Inválidos!");
            }
        }
    }//GEN-LAST:event_jbCadastrarActionPerformed

    private void jbSelecionarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelecionarMatriculaActionPerformed
        InterfaceRelatório form = new InterfaceRelatório(2, this);
        form.setLocation((desktop.getSize().width - form.getSize().width) / 2, (desktop.getSize().height - form.getSize().height) / 2);
        desktop.add(form);
        form.setVisible(true);
    }//GEN-LAST:event_jbSelecionarMatriculaActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        
    }//GEN-LAST:event_formFocusGained

    public void limpaCampos() {
        jtfCodigo.setText("");
        jtfMatriculaAluno.setText("");
        jtfCodCurso.setText("");
    }   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbCadastrar;
    private javax.swing.JButton jbFechar;
    private javax.swing.JButton jbSelecionarAluno;
    private javax.swing.JButton jbSelecionarCurso;
    private javax.swing.JButton jbSelecionarMatricula;
    private javax.swing.JTextField jtfCodCurso;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfData;
    private javax.swing.JTextField jtfMatriculaAluno;
    // End of variables declaration//GEN-END:variables
}
